### ISSUE TITLE
page does not load resources in production

### ISSUE THREAD

**Issue by Alex-Cruz6** [FloresCnzls/CarritoJS#14]
Compañeros la página no esta cargando bien los recursos.

![image](https://github.com/user-attachments/assets/9fc991c6-7fa7-44e8-988c-f7a217433586)

**Comment by LudwinM16** [comment]
Se estaba usando mal la redireccion de las imagenes, borre la carpeta que no era y subi la carpeta de "recursos" que es la que tiene las imagenes nuevas.
